# Generated by Django 5.2.12 on 2026-04-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='requestlogs',
            name='core_reques_ip_addr_0f7d9a_idx',
        ),
        migrations.RenameField(
            model_name='requestlogs',
            old_name='ip_address',
            new_name='ip',
        ),
        migrations.AddIndex(
            model_name='requestlogs',
            index=models.Index(fields=['ip', 'timestamp'], name='core_reques_ip_73981e_idx'),
        ),
    ]
